version: '3.9'

services:
    db:
        image: 'postgres:alpine'
        env_file:
            - .env.db
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - 'db-data:/var/lib/postgresql/data'

volumes:
    db-data:
